config/routes.rb
Seatyourself::Application.routes.draw do
  get "customers/new"
  get "customers/create"
  resources :restaurants
  resources :customers, :only => [:new, :create, :edit]
  root :to => 'restaurants#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_secure_password
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def new
  	@customer = Customer.new
  end

  def create
  	@customer = Customer.new(customer_params)
  	if @customer.save
  		redirect_to restaurants_url, :notice => "Congratulations! You're now signed up!"
  	else
  		render "new"
  	end
  end

 end

private

def customer_params
	params.require(:customer).permit(:first_name, :last_name, :email, :telephone, :password, :password_confirmation)

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  	@restaurants = Restaurant.all
  end

  def new
  	@restaurant = Restaurant.new
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  end

  def edit
  	@restaurant = Restaurant.find(params[:id])
  end

  def update
  	@restaurant = Restaurant.find(params[:id])

  	if @restaurant.update_attributes(restaurant_params)
  		redirect_to "/restaurants/#{@restaurant.id}"
  	else
  		render :edit
  	end
  end

  def create
  	@restaurant = Restaurant.new(restaurant_params)

  	if @restaurant.save
  		redirect_to restaurants_url
  	else
  		render :new
  	end
  end

  end

private

def restaurant_params
	params.require(:restaurant).permit(:name, :address, :category, :summary)

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/customers/new.html.erb
<h1>Sign up</h1>

<%= form_for @customer do |f| %>
	<% if @customer.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @customer.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

<div class="field">
	<%= f.label :first_name %><br />
	<%= f.text_field :first_name %>
</div>

<div class="field">
	<%= f.label :last_name %><br />
	<%= f.text_field :last_name %>
</div>

<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</div>

<div class="field">
	<%= f.label :telephone %><br />
	<%= f.text_field :telephone %>
</div>

<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %>
</div>

<div class="field">
	<%= f.label :password_confirmation %><br />
	<%= f.password_field :password_confirmation %>
</div>

<div class"actions"><%= f.submit %></div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for (@restaurant) do |f| %>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :address %><br />
	<%= f.text_field :address %>
</div>

<div class="field">
	<%= f.label :category %><br />
	<%= f.text_field :category %>
</div>

<div class="field">
	<%= f.label :summary %><br />
	<%= f.text_area :summary %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back to Restaurants', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>SeatYourself <3</h1>

<p> <% @restaurants.each do |restaurant| %></p>
<p>Restaurant: <%= link_to restaurant[:name], "/restaurants/#{restaurant.id}"%></p>
<p><em>Category: <%= restaurant[:category] %></em></p>
<p>__________________</p>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back to Restaurants', restaurants_path %>

app/views/restaurants/show.html.erb
<h3><%= @restaurant[:name] %></h3><%= link_to "Edit", edit_restaurant_path %> | <%= link_to "Back to Restaurants", restaurants_path %><br />

<p><strong>Address: </strong><%= @restaurant[:address] %><br /></p>
<p><strong>Cateogry: </strong><%= @restaurant[:category] %><br /></p>
<p><strong>Summary: </strong><%= @restaurant[:summary] %></p>